# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from perian import schemas  # noqa: F401


class BandwidthSla(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "Guaranteed": "GUARANTEED",
            "Not_Guaranteed": "NOT_GUARANTEED",
            "Minimum_Guaranteed": "MINIMUM_GUARANTEED",
            "Undefined": "UNDEFINED",
        }
    
    @schemas.classproperty
    def GUARANTEED(cls):
        return cls("Guaranteed")
    
    @schemas.classproperty
    def NOT_GUARANTEED(cls):
        return cls("Not_Guaranteed")
    
    @schemas.classproperty
    def MINIMUM_GUARANTEED(cls):
        return cls("Minimum_Guaranteed")
    
    @schemas.classproperty
    def UNDEFINED(cls):
        return cls("Undefined")
