# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from perian import schemas  # noqa: F401


class StorageType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "NVME": "NVME",
            "SSD": "SSD",
            "HDD": "HDD",
            "UNDEFINED": "UNDEFINED",
        }
    
    @schemas.classproperty
    def NVME(cls):
        return cls("NVME")
    
    @schemas.classproperty
    def SSD(cls):
        return cls("SSD")
    
    @schemas.classproperty
    def HDD(cls):
        return cls("HDD")
    
    @schemas.classproperty
    def UNDEFINED(cls):
        return cls("UNDEFINED")
