
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-02T06:52:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ddf07ecc567e9416f64577b69db8e6f1f12a924",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
