# Generated by Django 4.2.2 on 2023-08-29 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artd_product", "0006_rootcategory_json_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="special_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="special_price_from",
        ),
        migrations.RemoveField(
            model_name="product",
            name="special_price_to",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
