# Generated by Django 4.1.9 on 2023-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0008_remove_salesforceoppportunity_updateddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceoppportunity',
            name='ServiceLevel1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
