
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T15:22:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d1a0a4da85935b8b0a9afd763ba3bca9e3003c6",
 "version": "0.7.0-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
