
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T10:49:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "010be6c79ed124ef9ec0c6a0b74938359943f91a",
 "version": "5.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
