# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import perian
from perian.model.create_job_success import CreateJobSuccess
from perian import configuration


class TestCreateJobSuccess(unittest.TestCase):
    """CreateJobSuccess unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
