import ghidra.app.plugin.core.debug.service.rmi.trace
import java.lang
import java.util


class RemoteMethodRegistry(object):




    def __init__(self): ...



    def all(self) -> java.util.Map: ...

    def equals(self, __a0: object) -> bool: ...

    def get(self, __a0: unicode) -> ghidra.app.plugin.core.debug.service.rmi.trace.RemoteMethod: ...

    def getByAction(self, __a0: ghidra.app.plugin.core.debug.service.rmi.trace.RemoteMethod.Action) -> java.util.Set: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

