# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DashboardResponse(Model):
    """DashboardResponse.

    :param dashboard_id: The dashboard identifier
    :type dashboard_id: int
    :param dashboard_info: The dashboard info
    :type dashboard_info: str
    :param description: The dashboard description
    :type description: str
    :param type: The dashboard type
    :type type: str
    :param created_by:
    :type created_by: ~energycap.sdk.models.UserChild
    :param created_date: The date and time the dashboard was created
    :type created_date: datetime
    :param modified_date: The date and time of the most recent modification
    :type modified_date: datetime
    :param shared: Flag to indicate if the dashboard is shared at all
     This means the dashboard is shared with everyone, shared with a user, or
     shared with a user group
    :type shared: bool
    :param visible: Flag to indicate if dashboard should show in the caller's
     tree
    :type visible: bool
    :param last_viewed: The date and time of the last time this dashboard was
     viewed by the caller
    :type last_viewed: datetime
    :param key: If the dashboard is public, this value holds the public key
     that allows the dashboard to be embedded
    :type key: str
    :param public: Flag to indicate if the dashboard is public
    :type public: bool
    :param dashboard_global_settings:
    :type dashboard_global_settings:
     ~energycap.sdk.models.DashboardGlobalSettings
    """

    _attribute_map = {
        'dashboard_id': {'key': 'dashboardId', 'type': 'int'},
        'dashboard_info': {'key': 'dashboardInfo', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'UserChild'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'modified_date': {'key': 'modifiedDate', 'type': 'iso-8601'},
        'shared': {'key': 'shared', 'type': 'bool'},
        'visible': {'key': 'visible', 'type': 'bool'},
        'last_viewed': {'key': 'lastViewed', 'type': 'iso-8601'},
        'key': {'key': 'key', 'type': 'str'},
        'public': {'key': 'public', 'type': 'bool'},
        'dashboard_global_settings': {'key': 'dashboardGlobalSettings', 'type': 'DashboardGlobalSettings'},
    }

    def __init__(self, **kwargs):
        super(DashboardResponse, self).__init__(**kwargs)
        self.dashboard_id = kwargs.get('dashboard_id', None)
        self.dashboard_info = kwargs.get('dashboard_info', None)
        self.description = kwargs.get('description', None)
        self.type = kwargs.get('type', None)
        self.created_by = kwargs.get('created_by', None)
        self.created_date = kwargs.get('created_date', None)
        self.modified_date = kwargs.get('modified_date', None)
        self.shared = kwargs.get('shared', None)
        self.visible = kwargs.get('visible', None)
        self.last_viewed = kwargs.get('last_viewed', None)
        self.key = kwargs.get('key', None)
        self.public = kwargs.get('public', None)
        self.dashboard_global_settings = kwargs.get('dashboard_global_settings', None)
