error_messages = {
    "ZeroDivisionError": {"detail": "Erreur de division par zéro.", "fix": "Vérifiez le diviseur dans votre opération de division."},
    "ValueError": {"detail": "Erreur de valeur non valide.", "fix": "Assurez-vous de fournir une valeur valide."},
    "TypeError": {"detail": "Erreur de type de données.", "fix": "Assurez-vous d'utiliser le bon type de données."},
    "KeyError": {"detail": "Erreur de clé.", "fix": "Assurez-vous que la clé est correcte."},
    "FileNotFoundError": {"detail": "Erreur de fichier introuvable.", "fix": "Vérifiez le chemin du fichier ou créez-le."},
    "IndexError": {"detail": "Erreur d'indice.", "fix": "Assurez-vous d'utiliser le bon indice."},
    "AssertionError": {"detail": "Erreur d'assertion.", "fix": "Revue de votre déclaration d'assertion."},
    "AttributeError": {"detail": "Erreur d'attribut.", "fix": "Assurez-vous d'utiliser le bon attribut."},
    "IOError": {"detail": "Erreur d'entrée/sortie.", "fix": "Vérifiez vos opérations de fichier."},
    "NameError": {"detail": "Erreur de nommage.", "fix": "Vérifiez le nom de votre variable ou de votre fonction."},
    "ImportError": {"detail": "Erreur d'importation.", "fix": "Vérifiez le chemin d'importation."},
    "ModuleNotFoundError": {"detail": "Module non trouvé erreur.", "fix": "Assurez-vous que le module est installé."},
    "MemoryError": {"detail": "Erreur de mémoire.", "fix": "Réduisez l'utilisation de la mémoire ou optimisez-la."},
    "SyntaxError": {"detail": "Erreur de syntaxe.", "fix": "Vérifiez et corrigez votre syntaxe."},
    "IndentationError": {"detail": "Erreur d'indentation.", "fix": "Ajustez correctement les indentations."},
    "EOFError": {"detail": "Erreur de fin de fichier.", "fix": "Vérifiez si vous avez atteint la fin du fichier."},
    "ArithmeticError": {"detail": "Erreur arithmétique.", "fix": "Revue de vos opérations arithmétiques."},
    "FileExistsError": {"detail": "Fichier existe déjà erreur.", "fix": "Utilisez un nom de fichier différent ou supprimez le fichier existant."}
}
