# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import perian
from perian.paths.selection_get_flavors import post  # noqa: E501
from perian import configuration, schemas, api_client

from .. import ApiTestMixin


class TestSelectionGetFlavors(ApiTestMixin, unittest.TestCase):
    """
    SelectionGetFlavors unit test stubs
        Get Flavors  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
