# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PlaceSizeChild(Model):
    """PlaceSizeChild.

    :param place_size_id:
    :type place_size_id: int
    :param begin_date:
    :type begin_date: datetime
    :param end_date:
    :type end_date: datetime
    :param value:
    :type value: float
    :param unit_id:
    :type unit_id: int
    :param unit_code:  <span class='property-internal'>Must be between 0 and
     16 characters</span> <span class='property-internal'>Must be between 0 and
     16 characters</span>
    :type unit_code: str
    :param unit_info:  <span class='property-internal'>Must be between 0 and
     32 characters</span> <span class='property-internal'>Must be between 0 and
     32 characters</span>
    :type unit_info: str
    """

    _validation = {
        'unit_code': {'max_length': 16, 'min_length': 0},
        'unit_info': {'max_length': 32, 'min_length': 0},
    }

    _attribute_map = {
        'place_size_id': {'key': 'placeSizeId', 'type': 'int'},
        'begin_date': {'key': 'beginDate', 'type': 'iso-8601'},
        'end_date': {'key': 'endDate', 'type': 'iso-8601'},
        'value': {'key': 'value', 'type': 'float'},
        'unit_id': {'key': 'unitId', 'type': 'int'},
        'unit_code': {'key': 'unitCode', 'type': 'str'},
        'unit_info': {'key': 'unitInfo', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(PlaceSizeChild, self).__init__(**kwargs)
        self.place_size_id = kwargs.get('place_size_id', None)
        self.begin_date = kwargs.get('begin_date', None)
        self.end_date = kwargs.get('end_date', None)
        self.value = kwargs.get('value', None)
        self.unit_id = kwargs.get('unit_id', None)
        self.unit_code = kwargs.get('unit_code', None)
        self.unit_info = kwargs.get('unit_info', None)
