import java.lang
import java.util


class DebuggerWorkflowService(object):








    def disableBots(self, __a0: java.util.Set) -> None: ...

    def enableBots(self, __a0: java.util.Set) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllBots(self) -> java.util.Set: ...

    def getClass(self) -> java.lang.Class: ...

    def getDisabledBots(self) -> java.util.Set: ...

    def getEnabledBots(self) -> java.util.Set: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allBots(self) -> java.util.Set: ...

    @property
    def disabledBots(self) -> java.util.Set: ...

    @property
    def enabledBots(self) -> java.util.Set: ...