import ghidra.framework.options.annotation
import java.lang
import java.lang.annotation


class DebuggerBotInfo(java.lang.annotation.Annotation, object):








    def annotationType(self) -> java.lang.Class: ...

    def description(self) -> unicode: ...

    def details(self) -> unicode: ...

    def enabledByDefault(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def help(self) -> ghidra.framework.options.annotation.HelpInfo: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

