# Generated by Django 4.2.2 on 2023-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_product", "0005_alter_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootcategory",
            name="json_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Enter the json data of the root category",
                null=True,
                verbose_name="Json data",
            ),
        ),
    ]
