
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T09:42:15+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "54d21faad8a205d8e81906cc139df206f50c8343",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
