
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-03T10:02:04+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "0745dd0e15105214864d01058e68d57b73307947",
 "version": "2.6.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
