# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Product(Model):
    """Product.

    :param product_id: The product identifier
    :type product_id: int
    :param product_code: The product code
    :type product_code: str
    :param product_info: The product info
    :type product_info: str
    """

    _attribute_map = {
        'product_id': {'key': 'productId', 'type': 'int'},
        'product_code': {'key': 'productCode', 'type': 'str'},
        'product_info': {'key': 'productInfo', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Product, self).__init__(**kwargs)
        self.product_id = kwargs.get('product_id', None)
        self.product_code = kwargs.get('product_code', None)
        self.product_info = kwargs.get('product_info', None)
