
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-03T02:09:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9b9018a0d7b11ef3d8566c29dc237ab49c9c444",
 "version": "0.18.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
