from enum import Enum


class Command(Enum):
    SET = "SET"
    RM = "RM"
    SET_EVENT = "SET_EVENT"
    GET = "GET"
    PGET = "PGET"
    SUBSCRIBE = "SUBSCRIBE"
    PSUBSCRIBE = "PSUBSCRIBE"
    ADD_DATABASE = "ADD_DATABASE"
    DEL_DATABASE = "DEL_DATABASE"
    ADD_ROLE = "ADD_ROLE"
    DEL_ROLE = "DEL_ROLE"
    ADD_USER = "ADD_USER"
    DEL_USER = "DEL_USER"
    SHOW = "SHOW"
    VARIABLES = "VARIABLES"
    LOAD_LICENSE = "LOAD_LICENSE"
    CONFIG = "CONFIG"
