
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-02T06:17:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "11deab400884e4fd3c857dd1284fd2a105a91b23",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
