# Generated by Django 4.2.2 on 2023-08-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artd_product", "0004_category_root_category_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the Parent category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_product.category",
                verbose_name="Parent category",
            ),
        ),
    ]
