# Generated by Django 4.2.2 on 2023-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "artd_product",
            "0007_remove_product_price_remove_product_special_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.SlugField(
                help_text="Enter the sku of the product",
                max_length=250,
                verbose_name="Sku",
            ),
        ),
    ]
