# Generated by Django 4.1.9 on 2023-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0006_alter_salesforceoppportunity_closedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceoppportunity',
            name='CreatedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='salesforceoppportunity',
            name='UPdatedDate',
            field=models.DateField(null=True),
        ),
    ]
