from typing import List
import ghidra.program.model.address
import java.lang


class ProgramLoadImage(object):




    def __init__(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.pcode.memstate.MemoryFaultHandler): ...



    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInitializedAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def read(self, __a0: List[int], __a1: int, __a2: ghidra.program.model.address.Address, __a3: int, __a4: bool) -> List[int]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def write(self, __a0: List[int], __a1: int, __a2: ghidra.program.model.address.Address, __a3: int) -> None: ...

    @property
    def initializedAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...