# coding: utf-8

"""
    Corva Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from corva_data_assets.models.corva_asset_rig_id import CorvaAssetRigId  # noqa: E501

class TestCorvaAssetRigId(unittest.TestCase):
    """CorvaAssetRigId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorvaAssetRigId:
        """Test CorvaAssetRigId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorvaAssetRigId`
        """
        model = CorvaAssetRigId()  # noqa: E501
        if include_optional:
            return CorvaAssetRigId(
            )
        else:
            return CorvaAssetRigId(
        )
        """

    def testCorvaAssetRigId(self):
        """Test CorvaAssetRigId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
