__title__ = 'muiscaenergy_common'
__version__ = '0.0.3'
__author__ = 'Jairo Hernando Cervantes Garcia'
__email__ = 'muiscaenergy@gmail.com'
__license__ = 'MIT license'
__description__ = 'common functions for muiscaenergy projects'
__url__ = 'https://pypi.org/project/'
