# coding: utf-8

"""
    Corva API

    The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API

    The version of the OpenAPI document: v2.146.0
    Contact: support@corva.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from corva_assets.models.asset_attributes import AssetAttributes  # noqa: E501

class TestAssetAttributes(unittest.TestCase):
    """AssetAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetAttributes:
        """Test AssetAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetAttributes`
        """
        model = AssetAttributes()  # noqa: E501
        if include_optional:
            return AssetAttributes(
                name = '',
                status = '',
                state = '',
                api_number = '',
                county = '',
                basin = '',
                area = '',
                contractor_name = '',
                directional_driller = '',
                mud_company = '',
                customer_well_id = '',
                original_well_id = 1.337,
                original_well_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                visible_rerun_id = '',
                source_well = corva_assets.models.asset_attributes_source_well.Asset_attributes_source_well(
                    id = '', 
                    name = '', )
            )
        else:
            return AssetAttributes(
        )
        """

    def testAssetAttributes(self):
        """Test AssetAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
