# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CollectionResponse(Model):
    """CollectionResponse.

    :param collection_id: The collection identifier
    :type collection_id: int
    :param collection_code: The collection code
    :type collection_code: str
    :param collection_info: The collection info
    :type collection_info: str
    :param note: The collection description
    :type note: str
    :param collection_icon:
    :type collection_icon: ~energycap.sdk.models.Icon
    :param parent:
    :type parent: ~energycap.sdk.models.CollectionChild
    :param collections: An array of child collections
    :type collections: list[~energycap.sdk.models.CollectionChild]
    :param emission_sources: An array of child emission sources
    :type emission_sources:
     list[~energycap.sdk.models.CollectionEmissionSourceChild]
    """

    _attribute_map = {
        'collection_id': {'key': 'collectionId', 'type': 'int'},
        'collection_code': {'key': 'collectionCode', 'type': 'str'},
        'collection_info': {'key': 'collectionInfo', 'type': 'str'},
        'note': {'key': 'note', 'type': 'str'},
        'collection_icon': {'key': 'collectionIcon', 'type': 'Icon'},
        'parent': {'key': 'parent', 'type': 'CollectionChild'},
        'collections': {'key': 'collections', 'type': '[CollectionChild]'},
        'emission_sources': {'key': 'emissionSources', 'type': '[CollectionEmissionSourceChild]'},
    }

    def __init__(self, **kwargs):
        super(CollectionResponse, self).__init__(**kwargs)
        self.collection_id = kwargs.get('collection_id', None)
        self.collection_code = kwargs.get('collection_code', None)
        self.collection_info = kwargs.get('collection_info', None)
        self.note = kwargs.get('note', None)
        self.collection_icon = kwargs.get('collection_icon', None)
        self.parent = kwargs.get('parent', None)
        self.collections = kwargs.get('collections', None)
        self.emission_sources = kwargs.get('emission_sources', None)
