# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11vectorindex.proto\x12\x0bvectorindex\"c\n\x05_Item\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x06vector\x18\x02 \x01(\x0b\x32\x14.vectorindex._Vector\x12(\n\x08metadata\x18\x03 \x03(\x0b\x32\x16.vectorindex._Metadata\"M\n\x14_AddItemBatchRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12!\n\x05items\x18\x02 \x03(\x0b\x32\x12.vectorindex._Item\".\n\x15_AddItemBatchResponse\x12\x15\n\rerror_indices\x18\x01 \x03(\r\":\n\x17_DeleteItemBatchRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12\x0b\n\x03ids\x18\x02 \x03(\t\"\x1a\n\x18_DeleteItemBatchResponse\"\x1b\n\x07_Vector\x12\x10\n\x08\x65lements\x18\x01 \x03(\x02\";\n\t_Metadata\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x42\x07\n\x05value\"m\n\x10_MetadataRequest\x12\x32\n\x04some\x18\x02 \x01(\x0b\x32\".vectorindex._MetadataRequest.SomeH\x00\x1a\x16\n\x04Some\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x1a\x05\n\x03\x41llB\x06\n\x04kind\"\x97\x01\n\x0e_SearchRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\r\x12*\n\x0cquery_vector\x18\x03 \x01(\x0b\x32\x14.vectorindex._Vector\x12\x36\n\x0fmetadata_fields\x18\x04 \x01(\x0b\x32\x1d.vectorindex._MetadataRequest\"T\n\n_SearchHit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12(\n\x08metadata\x18\x03 \x03(\x0b\x32\x16.vectorindex._Metadata\"8\n\x0f_SearchResponse\x12%\n\x04hits\x18\x01 \x03(\x0b\x32\x17.vectorindex._SearchHit2\x8f\x02\n\x0bVectorIndex\x12W\n\x0c\x41\x64\x64ItemBatch\x12!.vectorindex._AddItemBatchRequest\x1a\".vectorindex._AddItemBatchResponse\"\x00\x12`\n\x0f\x44\x65leteItemBatch\x12$.vectorindex._DeleteItemBatchRequest\x1a%.vectorindex._DeleteItemBatchResponse\"\x00\x12\x45\n\x06Search\x12\x1b.vectorindex._SearchRequest\x1a\x1c.vectorindex._SearchResponse\"\x00\x62\x06proto3')



__ITEM = DESCRIPTOR.message_types_by_name['_Item']
__ADDITEMBATCHREQUEST = DESCRIPTOR.message_types_by_name['_AddItemBatchRequest']
__ADDITEMBATCHRESPONSE = DESCRIPTOR.message_types_by_name['_AddItemBatchResponse']
__DELETEITEMBATCHREQUEST = DESCRIPTOR.message_types_by_name['_DeleteItemBatchRequest']
__DELETEITEMBATCHRESPONSE = DESCRIPTOR.message_types_by_name['_DeleteItemBatchResponse']
__VECTOR = DESCRIPTOR.message_types_by_name['_Vector']
__METADATA = DESCRIPTOR.message_types_by_name['_Metadata']
__METADATAREQUEST = DESCRIPTOR.message_types_by_name['_MetadataRequest']
__METADATAREQUEST_SOME = __METADATAREQUEST.nested_types_by_name['Some']
__METADATAREQUEST_ALL = __METADATAREQUEST.nested_types_by_name['All']
__SEARCHREQUEST = DESCRIPTOR.message_types_by_name['_SearchRequest']
__SEARCHHIT = DESCRIPTOR.message_types_by_name['_SearchHit']
__SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['_SearchResponse']
_Item = _reflection.GeneratedProtocolMessageType('_Item', (_message.Message,), {
  'DESCRIPTOR' : __ITEM,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._Item)
  })
_sym_db.RegisterMessage(_Item)

_AddItemBatchRequest = _reflection.GeneratedProtocolMessageType('_AddItemBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : __ADDITEMBATCHREQUEST,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._AddItemBatchRequest)
  })
_sym_db.RegisterMessage(_AddItemBatchRequest)

_AddItemBatchResponse = _reflection.GeneratedProtocolMessageType('_AddItemBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : __ADDITEMBATCHRESPONSE,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._AddItemBatchResponse)
  })
_sym_db.RegisterMessage(_AddItemBatchResponse)

_DeleteItemBatchRequest = _reflection.GeneratedProtocolMessageType('_DeleteItemBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : __DELETEITEMBATCHREQUEST,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._DeleteItemBatchRequest)
  })
_sym_db.RegisterMessage(_DeleteItemBatchRequest)

_DeleteItemBatchResponse = _reflection.GeneratedProtocolMessageType('_DeleteItemBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : __DELETEITEMBATCHRESPONSE,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._DeleteItemBatchResponse)
  })
_sym_db.RegisterMessage(_DeleteItemBatchResponse)

_Vector = _reflection.GeneratedProtocolMessageType('_Vector', (_message.Message,), {
  'DESCRIPTOR' : __VECTOR,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._Vector)
  })
_sym_db.RegisterMessage(_Vector)

_Metadata = _reflection.GeneratedProtocolMessageType('_Metadata', (_message.Message,), {
  'DESCRIPTOR' : __METADATA,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._Metadata)
  })
_sym_db.RegisterMessage(_Metadata)

_MetadataRequest = _reflection.GeneratedProtocolMessageType('_MetadataRequest', (_message.Message,), {

  'Some' : _reflection.GeneratedProtocolMessageType('Some', (_message.Message,), {
    'DESCRIPTOR' : __METADATAREQUEST_SOME,
    '__module__' : 'vectorindex_pb2'
    # @@protoc_insertion_point(class_scope:vectorindex._MetadataRequest.Some)
    })
  ,

  'All' : _reflection.GeneratedProtocolMessageType('All', (_message.Message,), {
    'DESCRIPTOR' : __METADATAREQUEST_ALL,
    '__module__' : 'vectorindex_pb2'
    # @@protoc_insertion_point(class_scope:vectorindex._MetadataRequest.All)
    })
  ,
  'DESCRIPTOR' : __METADATAREQUEST,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._MetadataRequest)
  })
_sym_db.RegisterMessage(_MetadataRequest)
_sym_db.RegisterMessage(_MetadataRequest.Some)
_sym_db.RegisterMessage(_MetadataRequest.All)

_SearchRequest = _reflection.GeneratedProtocolMessageType('_SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : __SEARCHREQUEST,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._SearchRequest)
  })
_sym_db.RegisterMessage(_SearchRequest)

_SearchHit = _reflection.GeneratedProtocolMessageType('_SearchHit', (_message.Message,), {
  'DESCRIPTOR' : __SEARCHHIT,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._SearchHit)
  })
_sym_db.RegisterMessage(_SearchHit)

_SearchResponse = _reflection.GeneratedProtocolMessageType('_SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : __SEARCHRESPONSE,
  '__module__' : 'vectorindex_pb2'
  # @@protoc_insertion_point(class_scope:vectorindex._SearchResponse)
  })
_sym_db.RegisterMessage(_SearchResponse)

_VECTORINDEX = DESCRIPTOR.services_by_name['VectorIndex']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  __ITEM._serialized_start=34
  __ITEM._serialized_end=133
  __ADDITEMBATCHREQUEST._serialized_start=135
  __ADDITEMBATCHREQUEST._serialized_end=212
  __ADDITEMBATCHRESPONSE._serialized_start=214
  __ADDITEMBATCHRESPONSE._serialized_end=260
  __DELETEITEMBATCHREQUEST._serialized_start=262
  __DELETEITEMBATCHREQUEST._serialized_end=320
  __DELETEITEMBATCHRESPONSE._serialized_start=322
  __DELETEITEMBATCHRESPONSE._serialized_end=348
  __VECTOR._serialized_start=350
  __VECTOR._serialized_end=377
  __METADATA._serialized_start=379
  __METADATA._serialized_end=438
  __METADATAREQUEST._serialized_start=440
  __METADATAREQUEST._serialized_end=549
  __METADATAREQUEST_SOME._serialized_start=512
  __METADATAREQUEST_SOME._serialized_end=534
  __METADATAREQUEST_ALL._serialized_start=536
  __METADATAREQUEST_ALL._serialized_end=541
  __SEARCHREQUEST._serialized_start=552
  __SEARCHREQUEST._serialized_end=703
  __SEARCHHIT._serialized_start=705
  __SEARCHHIT._serialized_end=789
  __SEARCHRESPONSE._serialized_start=791
  __SEARCHRESPONSE._serialized_end=847
  _VECTORINDEX._serialized_start=850
  _VECTORINDEX._serialized_end=1121
# @@protoc_insertion_point(module_scope)
