
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T14:01:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccf26489ca3bc51f13d66d2cf3c6a8a91d28988a",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
