"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.5.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import delphix.api.gateway
from delphix.api.gateway.api.hyperscale_objects_api import HyperscaleObjectsApi  # noqa: E501


class TestHyperscaleObjectsApi(unittest.TestCase):
    """HyperscaleObjectsApi unit test stubs"""

    def setUp(self):
        self.api = HyperscaleObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_hyperscale_connector_by_id(self):
        """Test case for get_hyperscale_connector_by_id

        Get a Hyperscale Connector.  # noqa: E501
        """
        pass

    def test_get_hyperscale_connectors(self):
        """Test case for get_hyperscale_connectors

        Returns a list of Hyperscale Connectors.  # noqa: E501
        """
        pass

    def test_get_hyperscale_dataset_by_id(self):
        """Test case for get_hyperscale_dataset_by_id

        Get a Hyperscale Connector.  # noqa: E501
        """
        pass

    def test_get_hyperscale_dataset_tables_or_files(self):
        """Test case for get_hyperscale_dataset_tables_or_files

        Get the tables or files of a hyperscale dataset  # noqa: E501
        """
        pass

    def test_get_hyperscale_datasets(self):
        """Test case for get_hyperscale_datasets

        Returns a list of Hyperscale Datasets.  # noqa: E501
        """
        pass

    def test_get_hyperscale_mount_point_by_id(self):
        """Test case for get_hyperscale_mount_point_by_id

        Get a Hyperscale Mount Points.  # noqa: E501
        """
        pass

    def test_get_hyperscale_mount_points(self):
        """Test case for get_hyperscale_mount_points

        Returns a list of Hyperscale Mount Points.  # noqa: E501
        """
        pass

    def test_search_hyperscale_connectors(self):
        """Test case for search_hyperscale_connectors

        Search for Hyperscale Connectors.  # noqa: E501
        """
        pass

    def test_search_hyperscale_dataset_tables_or_files(self):
        """Test case for search_hyperscale_dataset_tables_or_files

        Search the tables or files of a hyperscale dataset  # noqa: E501
        """
        pass

    def test_search_hyperscale_datasets(self):
        """Test case for search_hyperscale_datasets

        Search for Hyperscale Datasets.  # noqa: E501
        """
        pass

    def test_search_hyperscale_mount_points(self):
        """Test case for search_hyperscale_mount_points

        Search for Hyperscale Mount Points.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
