
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-03T19:16:56+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "a3ed247b98ed81fde7f9cdaa738999111a1decb7",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
