VERSION_YEAR = 2023
VERSION_MONTH = int('10')
VERSION_DAY = int('02')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202310020137
version_date = '2023/10/02 01:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
