# coding: utf-8

"""
    Corva Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr, conlist

class CorvaAssetTopHole(BaseModel):
    """
    CorvaAssetTopHole
    """
    raw: Optional[StrictStr] = None
    coordinates: Optional[conlist(Union[StrictFloat, StrictInt])] = None
    __properties = ["raw", "coordinates"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CorvaAssetTopHole:
        """Create an instance of CorvaAssetTopHole from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if raw (nullable) is None
        # and __fields_set__ contains the field
        if self.raw is None and "raw" in self.__fields_set__:
            _dict['raw'] = None

        # set to None if coordinates (nullable) is None
        # and __fields_set__ contains the field
        if self.coordinates is None and "coordinates" in self.__fields_set__:
            _dict['coordinates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CorvaAssetTopHole:
        """Create an instance of CorvaAssetTopHole from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CorvaAssetTopHole.parse_obj(obj)

        _obj = CorvaAssetTopHole.parse_obj({
            "raw": obj.get("raw"),
            "coordinates": obj.get("coordinates")
        })
        return _obj


