from ..connection.base_connection import BaseCloudConnection as BaseCloudConnection
from _typeshed import Incomplete
from edgeiq.app_config import AppConfig as AppConfig
from edgeiq.exceptions import ConnectionBlockedError as ConnectionBlockedError, ConnectionError as ConnectionError, PublishError as PublishError

DEFAULT_ROUTING_KEY: str
DEFAULT_RABBITMQ_HOST: str
DEFAULT_RABBITMQ_PORT: str

class RabbitMQConnection(BaseCloudConnection):
    def __new__(cls): ...
    connection: Incomplete
    channel: Incomplete
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def reconnect(self) -> None: ...
    def publish(self, message) -> None: ...
    def disconnect(self) -> None: ...
