
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-22T10:26:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ceb6eb28893f3861b4f2a6e54e98bde06a04860a",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
