"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces. Please note that the Python client library follows Python's naming convention of snake casing for fields, even though they may appear in camel case in the API specification.  # noqa: E501

    The version of the OpenAPI document: 4.83.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.workspace_create_request_subscription_subscription_item_ids import WorkspaceCreateRequestSubscriptionSubscriptionItemIds
globals()['WorkspaceCreateRequestSubscriptionSubscriptionItemIds'] = WorkspaceCreateRequestSubscriptionSubscriptionItemIds
from kdp_api.model.workspace_create_request_subscription import WorkspaceCreateRequestSubscription


class TestWorkspaceCreateRequestSubscription(unittest.TestCase):
    """WorkspaceCreateRequestSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceCreateRequestSubscription(self):
        """Test WorkspaceCreateRequestSubscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceCreateRequestSubscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
