"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces. Please note that the Python client library follows Python's naming convention of snake casing for fields, even though they may appear in camel case in the API specification.  # noqa: E501

    The version of the OpenAPI document: 4.83.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.attribute_assignment_create_request import AttributeAssignmentCreateRequest


class TestAttributeAssignmentCreateRequest(unittest.TestCase):
    """AttributeAssignmentCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeAssignmentCreateRequest(self):
        """Test AttributeAssignmentCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributeAssignmentCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
