# Generated by Django 4.1.9 on 2023-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0007_salesforceoppportunity_createddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforceoppportunity',
            name='UPdatedDate',
        ),
        migrations.AlterField(
            model_name='salesforceoppportunity',
            name='CreatedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salesforceoppportunity',
            name='UpdatedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
