# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BillUnexportOptions(Model):
    """BillUnexportOptions.

    All required parameters must be populated in order to send to Azure.

    :param export_mode: Required.  <span
     class='property-internal'>Required</span> <span
     class='property-internal'>One of ap, gl </span>
    :type export_mode: str
    """

    _validation = {
        'export_mode': {'required': True},
    }

    _attribute_map = {
        'export_mode': {'key': 'exportMode', 'type': 'str'},
    }

    def __init__(self, *, export_mode: str, **kwargs) -> None:
        super(BillUnexportOptions, self).__init__(**kwargs)
        self.export_mode = export_mode
