# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BillReversalRequest(Model):
    """BillReversalRequest.

    All required parameters must be populated in order to send to Azure.

    :param bill_ids: Required. Bill ids to reverse <span
     class='property-internal'>Required</span> <span
     class='property-internal'>Cannot be Empty</span>
    :type bill_ids: list[int]
    :param batch_settings:
    :type batch_settings: ~energycap.sdk.models.BatchCreate
    """

    _validation = {
        'bill_ids': {'required': True},
    }

    _attribute_map = {
        'bill_ids': {'key': 'billIds', 'type': '[int]'},
        'batch_settings': {'key': 'batchSettings', 'type': 'BatchCreate'},
    }

    def __init__(self, **kwargs):
        super(BillReversalRequest, self).__init__(**kwargs)
        self.bill_ids = kwargs.get('bill_ids', None)
        self.batch_settings = kwargs.get('batch_settings', None)
