# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NotificationSystemSettingsRequest(Model):
    """NotificationSystemSettingsRequest.

    All required parameters must be populated in order to send to Azure.

    :param allow_users_to_email_notifications: Required. Are user's allowed to
     get email notifications <span class='property-internal'>Required</span>
    :type allow_users_to_email_notifications: bool
    :param notification_settings: The list of notification settings and the
     configured value
     If a notification type is not passed the configured value will remain what
     it was set to <span class='property-internal'>Required (defined)</span>
    :type notification_settings:
     list[~energycap.sdk.models.NotificationSettingRequest]
    """

    _validation = {
        'allow_users_to_email_notifications': {'required': True},
    }

    _attribute_map = {
        'allow_users_to_email_notifications': {'key': 'allowUsersToEmailNotifications', 'type': 'bool'},
        'notification_settings': {'key': 'notificationSettings', 'type': '[NotificationSettingRequest]'},
    }

    def __init__(self, **kwargs):
        super(NotificationSystemSettingsRequest, self).__init__(**kwargs)
        self.allow_users_to_email_notifications = kwargs.get('allow_users_to_email_notifications', None)
        self.notification_settings = kwargs.get('notification_settings', None)
