
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T14:01:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "70e7f9a02f856e7b4f7c0e72cbc9aaa72c26e19a",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
