
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-02T15:27:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3ec9a5b7b888411d4a30c77a5ca3ff47c0bb068",
 "version": "5.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
