# Poor performer limits
# Bad CTR definitions: Higher than 2500 impression and less than 0.15 # CTR / 0 order
BAD_CTR_IMPRESSION_THRESHOLD = 2500  # Count
BAD_CTR_CTR_THRESHOLD = 0.15  # Percent
BAD_CTR_ORDERS_THRESHOLD = 0  # Count

# Bid override setting
ACOS_THRESHOLD = 35  # Percent

# Campaign constants
DEFAULT_CAMPAIGN_ACOS = 30
DEFAULT_CAMPAIGN_NAME_PREFIX = "Radium10 - ST - "
DEFAULT_EXACT_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Exact - " + str(DEFAULT_CAMPAIGN_ACOS)
DEFAULT_PHRASE_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Phrase - " + str(DEFAULT_CAMPAIGN_ACOS)
DEFAULT_BROAD_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Broad - " + str(DEFAULT_CAMPAIGN_ACOS)
