
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-02T13:44:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f34229fd6010de0cc3ad0998c32f88ffe9e51331",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
