# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: placeHolderApiVersion
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from iqs_client.configuration import Configuration


class ElementLinkRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'model_elements': 'list[ElementInCompartmentDescriptor]'
    }

    attribute_map = {
        'model_elements': 'modelElements'
    }

    def __init__(self, model_elements=None, local_vars_configuration=None):  # noqa: E501
        """ElementLinkRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._model_elements = None
        self.discriminator = None

        self.model_elements = model_elements

    @property
    def model_elements(self):
        """Gets the model_elements of this ElementLinkRequest.  # noqa: E501


        :return: The model_elements of this ElementLinkRequest.  # noqa: E501
        :rtype: list[ElementInCompartmentDescriptor]
        """
        return self._model_elements

    @model_elements.setter
    def model_elements(self, model_elements):
        """Sets the model_elements of this ElementLinkRequest.


        :param model_elements: The model_elements of this ElementLinkRequest.  # noqa: E501
        :type: list[ElementInCompartmentDescriptor]
        """
        if self.local_vars_configuration.client_side_validation and model_elements is None:  # noqa: E501
            raise ValueError("Invalid value for `model_elements`, must not be `None`")  # noqa: E501

        self._model_elements = model_elements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ElementLinkRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ElementLinkRequest):
            return True

        return self.to_dict() != other.to_dict()
