//wooden 1815 palisade castle desert steppe morning banners sundappled ::1 art by james gurney highly detailed intricate details brushstrokes expressive volumetric lighting 1850
//interior view of Medieval wooden flour mill, large grind stones, at night, a digital painting by Atey Ghailan, concept art --v 4 --upbeta --ar 3:2 --v 4 --no people, text, font, caption --q 2 --v 4 --upbeta --upbeta --upbeta
// /transparent turquise energy ghost flying behind medieval human, particles, full picture, highly detailed, dark fantasy, realistic, concept art, detailed forest background, light rays --ar 3:2 --v 4 --s 750 --q 0.25 --upbeta
//large knight wearing golden armor with blue trim wielding large sword standing by alter --s 250 --upbeta --ar 3:2 --upbeta - Upscaled (Beta) by @Maciek (fast, private)
//warp elf, electric, ice --upbeta --ar 3:2 --upbeta --upbeta --upbeta
//accursed witch stalking a foggy ruined village --upbeta --ar 3:2 --upbeta
//beautifully asian female martial artist, master of the 4 elements style, cultivator, heroic pose, character design, Detriot streets, street fighting, explosions, war, nighttime, burning, photography, hyper details, hyper-realistic, high quality, cinematic light, High contrast, --ar 3:2 --q 5 --upbeta --upbeta
//witches, group, ritual, pagan, fire, heathen, forest, goat --upbeta --ar 3:2 --upbeta
//https://s.mj.run/fu7AQsUZ5hM https://s.mj.run/uSGrhqj5L9s https://s.mj.run/6fBakCwRC-E wooden 1815 palisade castle desert steppe morning banners sundappled ::1 art by james gurney highly detailed intricate details brushstrokes expressive volumetric lighting 1850::1 --ar 3:2 --v 4 --upbeta
//viking front of a giant ghost, art by Martin Bergstrom, davokar forest, symbaroum artwork, fairy tale character, grimm's tales, vinking folklore, fair folk, cursed knight, seventh son, witch, hedge knight, thorn, templar, prios, beast, blight beast, abomination, hunter, sorcerer, crone, tribal, mask, poncho, symbar, ancient ruins, art by jakub rozalski, VHS film grain, grainy, vintage film, anamorphic lens, film grain, 35mm film, analogue photography, 16mm --q 1 --v 4 --upbeta --ar 3:2 --upbeta
//dark elf female warrior ride an infernal horse, side view, full body with legs, summer forest, daylight ultra detailed --ar 3:2 --q 5 --upbeta
//digital painting Samurai girl beauty young in action smile dynamic light on forest with fox outfit
//Young man with a long black braid, fire bender, black and red robes, martial art pose, full colour, temple background, line art --v 4 --upbeta
//https://s.mj.run/K8RqbN4MQLU, rogue, male, character, dressed in black leathers, changeling, dungeons and dragons, in a dark castle, hunting a victem, raymond swanland, --ar 2:3 --upbeta
//an icon for a dagger made of purple psychic energy --upbeta

export const STYLE_PARTS: string[] = [
  'Shield Maiden',
  'Color Grading',
  //"Editorial Photography",
  //"Depth of Field, DOF",
  'dynamic action scene',
  'card illustration',
  //"Megapixel",
  'epic',
  //"Tilt Blur",
  'magical',
  'marvel comics',
  'by Jujitsu Niki',
  'by laurie greasley',
  'manga style',
  'rule of thirds',
  'sunny day bright light god rays',
  'trending on pixiv',
  'a digital painting by Atey Ghailan',
  'mysterious atmosphere',
  //"disgaea",
  'cinematic composition',
  //"by Miyazaki",
  //"by Nausicaa Ghibli",
  'super detailed',
  'deviantart',
  'digital art',
  'fan art',
  'brutal',
  'hyper realistic',
  'hyperrealistic',
  'full picture',
  'realistic',
  'fantasy',
  "style of Peter Jackson's Lord of the rings",
  "style of Zack Snyder's 300",
  //"style of james cameron's terminator 2",
  'dramatic lighting',
  'cinematic lighting',
  'dark',
  'fable',
  'colourful',
  'Fantasy Flight Games',
  'Elder Scrolls',
  'beautiful',
  'Gorgeous',
  'sharp focus',
  'game illustration',
  'cover art',
  'concept art',
  'cinematic',
  'stylised',
  //"tilt shift",
  'funny',
  'symmetrical',
  'vector',
  'full body visible',
  'seen from a distance',
  'moody',
  'cute',
  'motion blurr',
  'show back of the character',
  'side view',
  'tpp, third person perspective',
  'top down view',
  'debris flying',
  'strategic perspective',
  'ground perspective',
  'first person perspective',
  'artstation',
  'in the style of david lynch',
  'elaborate dark red illustration by Mike Mignola',
  //"adorable",
  'Epic composition',
  'Close up',
  //"by Frank Franzetta",
  'Low angle',
  'Wide angle',
  'trending on artstation',
  'beautiful lighting',
  'stains',
  //"anthropomorphic",
  'red stains',
  'spotlight',
  //"Frazetta style",
  'in the spotlight',
  //"in Darkest Dungeon style",
  'in Diablo style',
  'in World of Warcraft style',
  //"in Elden Ring style",
  'in Lord of the rings style',
  'in Witcher style',
  'in Realistic Medieval Fantasy style',
  'an epic fantasy medieval setting',
  'a fantasy medieval setting',
  'close-up',
  //"by studio ghibli",
  //"by studio trigger",
  'by Bourassa',
  'by Raphael Lacoste',
  'painting by Akihiko Yoshida',
  //"by Moebius",
  'Blurred background',
  //"by Laurie Greasley",
  'in style of Jean-Baptiste Monge',
  'fiberoptic',
  'in Banner Saga style',
  'gradient',
  'stylised characters',
  'highly detailed',
  'dungeons and dragons scene',
  'in Vincent Dutrait style',
  //"in a Paul Gulacy style",
  'epic fantasy',
  'level game art for video game',
  'ultra detailed',
  'Videogame Concept art',
  'isometric',
  'isometric, close up',
  'Forgotten Realms',
  'DnD',
  'Dark fantasy',
  'High fantasy',
  //"ultra realistic",
  'characters out of focus',
  //"unreal engine 5",
  //"Tim burton Style",w
  'atmospheric light',
  'vibrant colors',
  '8K',
  'ink splatters',
  'Breath of The Wild',
  'render',
  'octane renderer',
  'high detail',
  'high detailed',
  'anime',

  'pixar',
  'fortnite',
  'clash of clans',
  'world of warcraft',
  'in style of dragon nest',
  'in the style of League of Legends',
  'in the style of Hearthstone',
  'in the style of ragnarok online',
  'in the style of Dragon Oath',
  'in the style of Final Fantasy',
  'in the style of Overwatch',
  'in the style of Sea of Thieves',
  'in the style of dungeon fighter online',
  'in the style of Guild Wars',
  'in the style of World of Warcraft',
  'in the style of Diablo',
  'in the style of Starcraft',
  'in the style of Heroes of the Storm',
  'in the style of Star Wars: The Old Republic',
  'in the style of Apex Legends',

  'fighting an opponent',
  'surrounded by figures',
  'figures fighting in the background',
  'figures in the background',

  'dynamic pose',
  'limb magic',
  'chivalric combat',
  'combat',
  'hacking and slashing',
  'fighting',
  'drops of dark red liquid flying',
  'dark red liquid dripping',
  'multiple characters in the background',
  'light rays hit a character who blows up breaks down to small particles',
  'action',
  'action shot',
  'night',
  'day',

  'duel',
  'medieval human',
  'Kung fu tournament',
  'fight',
  'epic medieval fantasy',
  'in a battle',
  'among others fighting',
  'occult',

  //"mute color",
];
