# coding: utf-8

"""
    Corva Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from corva_data_assets.models.corva_asset_top_hole import CorvaAssetTopHole  # noqa: E501

class TestCorvaAssetTopHole(unittest.TestCase):
    """CorvaAssetTopHole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorvaAssetTopHole:
        """Test CorvaAssetTopHole
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorvaAssetTopHole`
        """
        model = CorvaAssetTopHole()  # noqa: E501
        if include_optional:
            return CorvaAssetTopHole(
                raw = '31.71094,-102.03916',
                coordinates = [
                    31.71094
                    ]
            )
        else:
            return CorvaAssetTopHole(
        )
        """

    def testCorvaAssetTopHole(self):
        """Test CorvaAssetTopHole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
