import java.lang
import javax.swing.event
import javax.swing.table


class DbLargeTableModel(object, javax.swing.table.TableModel):




    def __init__(self, table: db.Table): ...



    def addTableModelListener(self, l: javax.swing.event.TableModelListener) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumnClass(self, columnIndex: int) -> java.lang.Class: ...

    def getColumnCount(self) -> int: ...

    def getColumnName(self, columnIndex: int) -> unicode: ...

    def getRowCount(self) -> int: ...

    def getValueAt(self, rowIndex: int, columnIndex: int) -> object: ...

    def hashCode(self) -> int: ...

    def isCellEditable(self, rowIndex: int, columnIndex: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeTableModelListener(self, l: javax.swing.event.TableModelListener) -> None: ...

    def setValueAt(self, aValue: object, rowIndex: int, columnIndex: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def columnCount(self) -> int: ...

    @property
    def rowCount(self) -> int: ...