import ghidra.app.plugin.core.debug.service.rmi.trace
import ghidra.trace.model
import java.lang
import java.net


class TraceRmiHandler(object):
    VERSION: unicode = u'10.4'



    def __init__(self, __a0: ghidra.app.plugin.core.debug.service.rmi.trace.TraceRmiPlugin, __a1: java.net.Socket): ...



    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLastSnapshot(self, __a0: ghidra.trace.model.Trace) -> long: ...

    def getMethods(self) -> ghidra.app.plugin.core.debug.service.rmi.trace.RemoteMethodRegistry: ...

    def getRemoteAddress(self) -> java.net.SocketAddress: ...

    def hashCode(self) -> int: ...

    def isClosed(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def receiveLoop(self) -> None: ...

    def start(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def waitClosed(self) -> None: ...

    @property
    def closed(self) -> bool: ...

    @property
    def methods(self) -> ghidra.app.plugin.core.debug.service.rmi.trace.RemoteMethodRegistry: ...

    @property
    def remoteAddress(self) -> java.net.SocketAddress: ...