__title__ = 'common'
__version__ = '0.0.1'
__author__ = 'Jairo Hernando Cervantes Garcia'
__email__ = 'muiscaenergy@gmail.com'
__license__ = 'MIT license'
__description__ = 'ISO/RTO data'
__url__ = 'https://github.com/cervantesjairo/ISO'