if(${EXECUTE_MOVE} STREQUAL "TRUE")
    #files to be moves
    file(GLOB FILES_TO_MOVE ${FILES_WITH_WILDCARD})
    file(COPY ${FILES_TO_MOVE} DESTINATION ${FILES_MOVE_DESTINATION})
    MESSAGE(-- COPIED ${FILES_TO_MOVE} FROM ${FILES_WITH_WILDCARD} TO ${FILES_MOVE_DESTINATION})
endif()