
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-05T17:38:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "706a4233c24e33673da16ec80b596b5cd191620c",
 "version": "0.7.0-rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
