# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\xea\xf01r'
full_git_hash = 'eaf031729b11834f377a98e550fe03798639c796'
git_branch = 'HEAD'
dirty = False
