import ghidra.pcode.emulate
import ghidra.pcode.pcoderaw
import ghidra.program.model.address
import java.lang


class BreakTableCallBack(object, ghidra.pcode.emulate.BreakTable):
    DEFAULT_NAME: unicode = u'*'



    def __init__(self, __a0: ghidra.app.plugin.processors.sleigh.SleighLanguage): ...



    def doAddressBreak(self, __a0: ghidra.program.model.address.Address) -> bool: ...

    def doPcodeOpBreak(self, __a0: ghidra.pcode.pcoderaw.PcodeOpRaw) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def registerAddressCallback(self, __a0: ghidra.program.model.address.Address, __a1: ghidra.pcode.emulate.BreakCallBack) -> None: ...

    def registerPcodeCallback(self, __a0: unicode, __a1: ghidra.pcode.emulate.BreakCallBack) -> None: ...

    def setEmulate(self, __a0: ghidra.pcode.emulate.Emulate) -> None: ...

    def toString(self) -> unicode: ...

    def unregisterAddressCallback(self, __a0: ghidra.program.model.address.Address) -> None: ...

    def unregisterPcodeCallback(self, __a0: unicode) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def emulate(self) -> None: ...  # No getter available.

    @emulate.setter
    def emulate(self, value: ghidra.pcode.emulate.Emulate) -> None: ...