# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomerResponse(Model):
    """CustomerResponse.

    :param customer_id: The customer identifier
    :type customer_id: int
    :param customer_code: The customer code
    :type customer_code: str
    :param customer_info: The customer info
    :type customer_info: str
    :param address:
    :type address: ~energycap.sdk.models.AddressChild
    """

    _attribute_map = {
        'customer_id': {'key': 'customerId', 'type': 'int'},
        'customer_code': {'key': 'customerCode', 'type': 'str'},
        'customer_info': {'key': 'customerInfo', 'type': 'str'},
        'address': {'key': 'address', 'type': 'AddressChild'},
    }

    def __init__(self, **kwargs):
        super(CustomerResponse, self).__init__(**kwargs)
        self.customer_id = kwargs.get('customer_id', None)
        self.customer_code = kwargs.get('customer_code', None)
        self.customer_info = kwargs.get('customer_info', None)
        self.address = kwargs.get('address', None)
