# coding: utf-8

# flake8: noqa
"""
    Corva API

    The Corva API is a powerful interface providing great flexibility and extensibility with Corva. Whether your needs are simple UI visualizations, data entry, replication/sync tasks, real-time stream processing, or complex machine learning CPU-intensive apps, the Corva API is the way to make it happen. Our concepts are split into three distinct silos: data apps, visualization apps, and a REST API

    The version of the OpenAPI document: v2.146.0
    Contact: support@corva.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from corva_assets.models.asset import Asset
from corva_assets.models.asset_attributes import AssetAttributes
from corva_assets.models.asset_attributes_source_well import AssetAttributesSourceWell
from corva_assets.models.assets import Assets
from corva_assets.models.authentication_error import AuthenticationError
from corva_assets.models.authorization_error import AuthorizationError
from corva_assets.models.not_found_error import NotFoundError
