import ghidra.util.datastruct
import java.lang
import java.lang.ref


class ListenerMap(object):
    CALLING_THREAD: java.util.concurrent.Executor = ghidra.util.datastruct.ListenerMap$1@23514c9e




    class ListenerEntry(java.lang.ref.WeakReference):




        def __init__(self, __a0: object): ...



        def clear(self) -> None: ...

        def enqueue(self) -> bool: ...

        def equals(self, __a0: object) -> bool: ...

        def get(self) -> object: ...

        def getClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def isEnqueued(self) -> bool: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        @staticmethod
        def reachabilityFence(__a0: object) -> None: ...

        def refersTo(self, __a0: object) -> bool: ...

        def toString(self) -> unicode: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...



    @overload
    def __init__(self, __a0: java.lang.Class): ...

    @overload
    def __init__(self, __a0: java.lang.Class, __a1: java.util.concurrent.Executor): ...



    @staticmethod
    def checkErr() -> None: ...

    def clear(self) -> None: ...

    @staticmethod
    def clearErr() -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def fire(self, __a0: java.lang.Class) -> object: ...

    def get(self, __a0: object) -> object: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def put(self, __a0: object, __a1: object) -> object: ...

    def putAll(self, __a0: ghidra.util.datastruct.ListenerMap) -> None: ...

    def remove(self, __a0: object) -> object: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def empty(self) -> bool: ...