# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dydxprotocol.perpetuals import tx_pb2 as dydxprotocol_dot_perpetuals_dot_tx__pb2


class MsgStub(object):
    """Msg defines the Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPremiumVotes = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/AddPremiumVotes',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.FromString,
                )
        self.CreatePerpetual = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/CreatePerpetual',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the Msg service.
    """

    def AddPremiumVotes(self, request, context):
        """AddPremiumVotes add new samples of the funding premiums to the
        application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePerpetual(self, request, context):
        """CreatePerpetual creates a new perpetual object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPremiumVotes': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPremiumVotes,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.SerializeToString,
            ),
            'CreatePerpetual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePerpetual,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dydxprotocol.perpetuals.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the Msg service.
    """

    @staticmethod
    def AddPremiumVotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dydxprotocol.perpetuals.Msg/AddPremiumVotes',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePerpetual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dydxprotocol.perpetuals.Msg/CreatePerpetual',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
