# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gdshop_proto/auth_provider/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%gdshop_proto/auth_provider/auth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0fSendCodeRequest\x12\x12\n\x05phone\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_phone\"P\n\x12TokenAcceptRequest\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06source\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_codeB\t\n\x07_source\"g\n\x0bJWTResponse\x12\x19\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rrefresh_token\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0f\n\r_access_tokenB\x10\n\x0e_refresh_token2\xbe\x01\n\x0c\x41uthProvider\x12;\n\x08SendCode\x12\x15.auth.SendCodeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x08GetToken\x12\x18.auth.TokenAcceptRequest\x1a\x11.auth.JWTResponse\"\x00\x12\x36\n\x0cRefreshToken\x12\x11.auth.JWTResponse\x1a\x11.auth.JWTResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdshop_proto.auth_provider.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENDCODEREQUEST']._serialized_start=76
  _globals['_SENDCODEREQUEST']._serialized_end=123
  _globals['_TOKENACCEPTREQUEST']._serialized_start=125
  _globals['_TOKENACCEPTREQUEST']._serialized_end=205
  _globals['_JWTRESPONSE']._serialized_start=207
  _globals['_JWTRESPONSE']._serialized_end=310
  _globals['_AUTHPROVIDER']._serialized_start=313
  _globals['_AUTHPROVIDER']._serialized_end=503
# @@protoc_insertion_point(module_scope)
