# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gdshop_proto.auth_provider import profile_pb2 as gdshop__proto_dot_auth__provider_dot_profile__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Change = channel.unary_unary(
                '/profile.ProfileService/Change',
                request_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.SerializeToString,
                response_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
                )
        self.Get = channel.unary_unary(
                '/profile.ProfileService/Get',
                request_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.SerializeToString,
                response_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
                )
        self.Delete = channel.unary_unary(
                '/profile.ProfileService/Delete',
                request_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Me = channel.unary_unary(
                '/profile.ProfileService/Me',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
                )
        self.AcceptEmail = channel.unary_unary(
                '/profile.ProfileService/AcceptEmail',
                request_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.EmailAcceptRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AcceptPhone = channel.unary_unary(
                '/profile.ProfileService/AcceptPhone',
                request_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.PhoneAcceptRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Me(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
                    response_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.FromString,
                    response_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Me': grpc.unary_unary_rpc_method_handler(
                    servicer.Me,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.SerializeToString,
            ),
            'AcceptEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptEmail,
                    request_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.EmailAcceptRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AcceptPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptPhone,
                    request_deserializer=gdshop__proto_dot_auth__provider_dot_profile__pb2.PhoneAcceptRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/Change',
            gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.SerializeToString,
            gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/Get',
            gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.SerializeToString,
            gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/Delete',
            gdshop__proto_dot_auth__provider_dot_profile__pb2.GetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Me(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/Me',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gdshop__proto_dot_auth__provider_dot_profile__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/AcceptEmail',
            gdshop__proto_dot_auth__provider_dot_profile__pb2.EmailAcceptRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/AcceptPhone',
            gdshop__proto_dot_auth__provider_dot_profile__pb2.PhoneAcceptRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
